site_name: Security Engineering Diaries
site_description: My Journey to Cloud Native Mastery
site_url: https://blog.z3cyber.tech
theme:
  name: material
  custom_dir: docs/blog/posts/overrides
  font:
    code: JetBrains Mono
    text: JetBrains
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: teal
        accent: deep orange
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: teal
        accent: deep orange
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
  - About: about.md
  - Tags: tags.md

plugins:
  - search
  - blog:
      categories_allowed:
        - Homelab
        - Cloud Security
        - Kubernetes
      post_url_format: "{slug}"
  - tags:
      tags_file: tags.md

extra_css:
  - extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/zazathomas
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zazathomas
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zazathomas

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: |
  &copy; 2025 <a href="https://github.com/zazathomas"  target="_blank" rel="noopener">Zaza Thomas</a>